-- ECOMMERCE PLATFORM - ORACLE DATABASE SCHEMA
-- USERS TABLE
CREATE TABLE USERS (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(20) NOT NULL CHECK (ROLE IN ('ADMIN', 'CUSTOMER')),
    MOBILE VARCHAR2(20) NOT NULL,
    ADDRESS VARCHAR2(255) NOT NULL,
    CITY VARCHAR2(50) NOT NULL,
    STATE VARCHAR2(50) NOT NULL,
    PINCODE VARCHAR2(6) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_ACTIVE NUMBER(1) DEFAULT 1 CHECK (IS_ACTIVE IN (0, 1))
);

-- Create sequence for USER IDs
CREATE SEQUENCE USER_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

-- Create indexes for USERS
CREATE INDEX IDX_USERS_EMAIL ON USERS(EMAIL);
CREATE INDEX IDX_USERS_ROLE ON USERS(ROLE);
CREATE INDEX IDX_USERS_CREATED ON USERS(CREATED_AT);

-- PRODUCTS TABLE
CREATE TABLE PRODUCTS (
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(255) NOT NULL,
    PRICE NUMBER(10, 2) NOT NULL CHECK (PRICE > 0),
    DESCRIPTION VARCHAR2(1000),
    CATEGORY VARCHAR2(100) NOT NULL,
    BRAND VARCHAR2(100) NOT NULL,
    STOCK NUMBER(10) DEFAULT 0 CHECK (STOCK >= 0),
    IMAGE_URL CLOB,
    RATING NUMBER(3, 2) DEFAULT 0 CHECK (RATING >= 0 AND RATING <= 5),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_ACTIVE NUMBER(1) DEFAULT 1 CHECK (IS_ACTIVE IN (0, 1))
);

-- Create sequence for PRODUCT IDs
CREATE SEQUENCE PRODUCT_SEQ
    START WITH 1
    INCREMENT BY 1
    NO CACHE;

-- Create indexes for PRODUCTS
CREATE INDEX IDX_PRODUCTS_CATEGORY ON PRODUCTS(CATEGORY);
CREATE INDEX IDX_PRODUCTS_BRAND ON PRODUCTS(BRAND);
CREATE INDEX IDX_PRODUCTS_PRICE ON PRODUCTS(PRICE);
CREATE INDEX IDX_PRODUCTS_STOCK ON PRODUCTS(STOCK);
CREATE INDEX IDX_PRODUCTS_RATING ON PRODUCTS(RATING);
CREATE INDEX IDX_PRODUCTS_ACTIVE ON PRODUCTS(IS_ACTIVE);
CREATE INDEX IDX_PRODUCTS_NAME ON PRODUCTS(UPPER(PRODUCT_NAME));

-- CATEGORIES TABLE
CREATE TABLE CATEGORIES (
    CATEGORY_ID NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(150) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR2(1000)
);

CREATE SEQUENCE CATEGORY_SEQ
    START WITH 1
    INCREMENT BY 1
    NO CACHE;

CREATE INDEX IDX_CATEGORIES_NAME ON CATEGORIES(UPPER(CATEGORY_NAME));

-- CART TABLE
CREATE TABLE CART (
    CART_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    QUANTITY NUMBER(10) NOT NULL CHECK (QUANTITY > 0),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CART_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_CART_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_CART_USER_PRODUCT UNIQUE (USER_ID, PRODUCT_ID)
);

-- Create sequence for CART IDs
CREATE SEQUENCE CART_SEQ
    START WITH 1
    INCREMENT BY 1
    NO CACHE;

-- Create indexes for CART
CREATE INDEX IDX_CART_USER ON CART(USER_ID);
CREATE INDEX IDX_CART_PRODUCT ON CART(PRODUCT_ID);

-- WISHLIST TABLE
CREATE TABLE WISHLIST (
    WISHLIST_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_WISH_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_WISH_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_WISHLIST_USER_PRODUCT UNIQUE (USER_ID, PRODUCT_ID)
);

-- Create sequence for WISHLIST IDs
CREATE SEQUENCE WISHLIST_SEQ
    START WITH 1
    INCREMENT BY 1
    NO CACHE;

-- Create indexes for WISHLIST
CREATE INDEX IDX_WISHLIST_USER ON WISHLIST(USER_ID);
CREATE INDEX IDX_WISHLIST_PRODUCT ON WISHLIST(PRODUCT_ID);

-- ORDERS TABLE
CREATE TABLE ORDERS (
    ORDER_ID NUMBER NOT NULL,
    ITEM_ID NUMBER PRIMARY KEY,
    PRODUCT_ID NUMBER NOT NULL,
    QUANTITY NUMBER(10) NOT NULL CHECK (QUANTITY > 0),
    PRICE NUMBER(10, 2) NOT NULL CHECK (PRICE > 0),
    STATUS VARCHAR2(20) DEFAULT 'PENDING' CHECK (STATUS IN ('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED')),
    USER_ID NUMBER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ORDERS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ORDERS_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

-- Create sequence for ORDER IDs
CREATE SEQUENCE ORDERS_SEQ
    START WITH 1
    INCREMENT BY 1
    NO CACHE;

-- Create indexes for ORDERS
CREATE INDEX IDX_ORDERS_ORDER_ID ON ORDERS(ORDER_ID);
CREATE INDEX IDX_ORDERS_USER ON ORDERS(USER_ID);
CREATE INDEX IDX_ORDERS_PRODUCT ON ORDERS(PRODUCT_ID);
CREATE INDEX IDX_ORDERS_STATUS ON ORDERS(STATUS);
CREATE INDEX IDX_ORDERS_CREATED ON ORDERS(CREATED_AT);
CREATE INDEX IDX_ORDERS_USER_CREATED ON ORDERS(USER_ID, CREATED_AT);

-- PAYMENTS TABLE
CREATE TABLE PAYMENTS (
    PAYMENT_ID NUMBER PRIMARY KEY,
    ORDER_ID NUMBER NOT NULL,
    PAYMENT_METHOD VARCHAR2(50) NOT NULL CHECK (PAYMENT_METHOD IN ('CREDIT_CARD', 'DEBIT_CARD', 'NET_BANKING', 'UPI', 'WALLET', 'COD')),
    PAYMENT_STATUS VARCHAR2(20) DEFAULT 'PENDING' CHECK (PAYMENT_STATUS IN ('PENDING', 'INITIATED', 'SUCCESS', 'FAILED', 'CANCELLED', 'REFUNDED')),
    AMOUNT NUMBER(10, 2) NOT NULL CHECK (AMOUNT > 0),
    TRANSACTION_ID VARCHAR2(100),
    RAZORPAY_ORDER_ID VARCHAR2(100),
    RAZORPAY_PAYMENT_ID VARCHAR2(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PAYMENTS_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_PAYMENTS_TRANSACTION UNIQUE (TRANSACTION_ID)
);

-- Create sequence for PAYMENT IDs
CREATE SEQUENCE PAYMENTS_SEQ
    START WITH 1
    INCREMENT BY 1
    NO CACHE;

-- Create indexes for PAYMENTS
CREATE INDEX IDX_PAYMENTS_ORDER ON PAYMENTS(ORDER_ID);
CREATE INDEX IDX_PAYMENTS_STATUS ON PAYMENTS(PAYMENT_STATUS);
CREATE INDEX IDX_PAYMENTS_METHOD ON PAYMENTS(PAYMENT_METHOD);
CREATE INDEX IDX_PAYMENTS_CREATED ON PAYMENTS(CREATED_AT);

-- AUDIT LOGS TABLE (for tracking changes)
CREATE TABLE AUDIT_LOGS (
    LOG_ID NUMBER PRIMARY KEY,
    ENTITY_TYPE VARCHAR2(50) NOT NULL,
    ENTITY_ID NUMBER NOT NULL,
    ACTION VARCHAR2(20) NOT NULL,
    USER_ID NUMBER,
    OLD_VALUES CLOB,
    NEW_VALUES CLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create sequence for AUDIT_LOGS
CREATE SEQUENCE AUDIT_LOG_SEQ
    START WITH 1
    INCREMENT BY 1
    NO CACHE;

-- Create indexes for AUDIT_LOGS
CREATE INDEX IDX_AUDIT_ENTITY ON AUDIT_LOGS(ENTITY_TYPE, ENTITY_ID);
CREATE INDEX IDX_AUDIT_USER ON AUDIT_LOGS(USER_ID);
CREATE INDEX IDX_AUDIT_CREATED ON AUDIT_LOGS(CREATED_AT);

-- View for order summary
CREATE OR REPLACE VIEW V_ORDER_SUMMARY AS
SELECT 
    o.ORDER_ID,
    o.USER_ID,
    u.EMAIL,
    u.NAME,
    COUNT(o.ITEM_ID) as ITEM_COUNT,
    SUM(o.QUANTITY) as TOTAL_QUANTITY,
    SUM(o.PRICE * o.QUANTITY) as TOTAL_AMOUNT,
    o.STATUS,
    o.CREATED_AT
FROM ORDERS o
JOIN USERS u ON o.USER_ID = u.ID
GROUP BY o.ORDER_ID, o.USER_ID, u.EMAIL, u.NAME, o.STATUS, o.CREATED_AT;

-- View for revenue by status
CREATE OR REPLACE VIEW V_REVENUE_BY_STATUS AS
SELECT 
    p.PAYMENT_STATUS,
    COUNT(p.PAYMENT_ID) as PAYMENT_COUNT,
    SUM(p.AMOUNT) as TOTAL_REVENUE
FROM PAYMENTS p
GROUP BY p.PAYMENT_STATUS;

-- View for product performance
CREATE OR REPLACE VIEW V_PRODUCT_PERFORMANCE AS
SELECT 
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY,
    p.BRAND,
    p.STOCK,
    NVL(COUNT(o.ITEM_ID), 0) as TIMES_ORDERED,
    NVL(SUM(o.QUANTITY), 0) as TOTAL_QUANTITY_SOLD,
    NVL(SUM(o.PRICE * o.QUANTITY), 0) as TOTAL_REVENUE
FROM PRODUCTS p
LEFT JOIN ORDERS o ON p.PRODUCT_ID = o.PRODUCT_ID AND o.STATUS != 'CANCELLED'
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME, p.CATEGORY, p.BRAND, p.STOCK;


COMMIT;
