-- Inventory management schema for Oracle 11g

CREATE TABLE INVENTORY (
    INVENTORY_ID NUMBER PRIMARY KEY,
    PRODUCT_ID NUMBER NOT NULL,
    AVAILABLE_STOCK NUMBER DEFAULT 0,
    RESERVED_STOCK NUMBER DEFAULT 0,
    LAST_UPDATED DATE
);

CREATE SEQUENCE INVENTORY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

ALTER TABLE INVENTORY ADD CONSTRAINT FK_INVENTORY_PRODUCT FOREIGN KEY (PRODUCT_ID)
    REFERENCES PRODUCTS (PRODUCT_ID);

ALTER TABLE INVENTORY ADD CONSTRAINT UQ_INVENTORY_PRODUCT UNIQUE (PRODUCT_ID);
