SELECT * FROM INVENTORY;
CREATE TABLE USERS(
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100),
    EMAIL VARCHAR2(100) UNIQUE,
    PASSWORD VARCHAR2(255),
    ROLE VARCHAR2(20)
);

SELECT * FROM USERS;

DESC USERS;

ALTER TABLE USERS
ADD (
    ADDRESS VARCHAR2(255),
    CITY VARCHAR2(100),
    STATE VARCHAR2(100),
    PINCODE VARCHAR2(10)
);


DELETE FROM USERS WHERE EMAIL='dinesh@gmail.com';

TRUNCATE TABLE USERS;

SELECT ID,EMAIL,PASSWORD,ROLE FROM USERS;

CREATE TABLE PRODUCTS(
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(200),
    DESCRIPTION VARCHAR2(1000),
    CATEGORY VARCHAR2(100),
    BRAND VARCHAR2(100),
    PRICE NUMBER(10,2),
    STOCK NUMBER,
    IMAGE_URL VARCHAR2(500),
    RATING NUMBER(2,1)
);

DESC PRODUCTS;

CREATE SEQUENCE PRODUCT_SEQ
START WITH 1
INCREMENT BY 1;

SELECT * FROM PRODUCTS;

ALTER TABLE PRODUCTS
ADD (
    CATEGORY  VARCHAR2(100),
    BRAND VARCHAR2(100),
    STOCK NUMBER,
    IMAGE_URL VARCHAR2(500),
    RATING NUMBER(2,1)
);

TRUNCATE TABLE PRODUCTS;

CREATE TABLE CART(
    CART_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER,
    PRODUCT_ID NUMBER,
    QUANTITY NUMBER

);

DESC CART;

CREATE SEQUENCE CART_SEQ;

ALTER TABLE CART RENAME COLUMN ID TO CART_ID;

TRUNCATE TABLE CART;

SELECT * FROM ORDERS;
TRUNCATE TABLE ORDERS;
DESC ORDERS;

ALTER TABLE ORDERS
ADD (
    ITEM_ID NUMBER PRIMARY KEY,
    PRODUCT_ID NUMBER,
    QUANTITY NUMBER,
    PRICE NUMBER(10,2)
);

ALTER TABLE ORDERS
ADD STATUS VARCHAR2(50);

CREATE SEQUENCE ORDERS_SEQ;

CREATE TABLE PAYMENTS(
    PAYMENT_ID NUMBER PRIMARY KEY,
    ORDER_ID NUMBER,
    PAYMENT_METHOD VARCHAR2(50),
    PAYMENT_STATUS VARCHAR2(50),
    AMOUNT NUMBER(10,2)
);

DESC PAYMENTS;

CREATE SEQUENCE PAYMENTS_SEQ;

CREATE TABLE WISHLIST(
    WISHLIST_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER,
    PRODUCT_ID NUMBER
);

DESC WISHLIST;

CREATE SEQUENCE WISHLIST_SEQ;

SELECT SEQUENCE_NAME
FROM USER_SEQUENCES;

SELECT SEQUENCE_NAME
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME='USER_SEQ';

CREATE SEQUENCE USER_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

SELECT USER_SEQ.NEXTVAL FROM DUAL;

DELETE FROM USERS;
COMMIT;

INSERT INTO USERS
(
 ID,
 NAME,
 EMAIL,
 PASSWORD,
 MOBILE,
 ADDRESS,
 CITY,
 STATE,
 PINCODE,
 ROLE
)
VALUES
(
 USER_SEQ.NEXTVAL,
 'Admin',
 'admin@gmail.com',
 '12345',
 '9999999999',
 'Hyderabad',
 'Hyderabad',
 'Telangana',
 '500001',
 'ADMIN'
);

COMMIT;

DELETE FROM USERS WHERE EMAIL = 'admin@gmail.com';

CREATE TABLE INVENTORY (
    INVENTORY_ID NUMBER PRIMARY KEY,
    PRODUCT_ID NUMBER NOT NULL,
    AVAILABLE_STOCK NUMBER DEFAULT 0,
    RESERVED_STOCK NUMBER DEFAULT 0,
    LAST_UPDATED DATE DEFAULT SYSDATE
);

CREATE SEQUENCE INVENTORY_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE;

INSERT INTO INVENTORY
(
    INVENTORY_ID,
    PRODUCT_ID,
    AVAILABLE_STOCK,
    RESERVED_STOCK,
    LAST_UPDATED
)
SELECT
    INVENTORY_SEQ.NEXTVAL,
    PRODUCT_ID,
    STOCK,
    0,
    SYSDATE
FROM PRODUCTS;

COMMIT;


CREATE OR REPLACE VIEW VW_TOP_SELLING_PRODUCTS AS
SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    SUM(o.QUANTITY) AS TOTAL_SOLD
FROM PRODUCTS p
JOIN ORDERS o
ON p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME;


CREATE OR REPLACE VIEW VW_MONTHLY_REVENUE AS
SELECT
    TO_CHAR(TRUNC(CREATED_AT,'MM'),'YYYY-MM') AS MONTH,
    SUM(PRICE * QUANTITY) AS REVENUE
FROM ORDERS
GROUP BY TRUNC(CREATED_AT,'MM');

CREATE OR REPLACE PROCEDURE SP_UPDATE_STOCK(
    p_product_id IN NUMBER,
    p_quantity IN NUMBER
)
AS
    v_stock NUMBER;
BEGIN
    SELECT STOCK
    INTO v_stock
    FROM PRODUCTS
    WHERE PRODUCT_ID = p_product_id;

    IF v_stock < p_quantity THEN
        RAISE_APPLICATION_ERROR(-20001,'Insufficient Stock');
    END IF;

    UPDATE PRODUCTS
    SET STOCK = STOCK - p_quantity
    WHERE PRODUCT_ID = p_product_id;

    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE SP_PLACE_ORDER(
    p_user_id IN NUMBER,
    p_product_id IN NUMBER,
    p_quantity IN NUMBER
)
AS
    v_price NUMBER;
BEGIN

    SELECT PRICE
    INTO v_price
    FROM PRODUCTS
    WHERE PRODUCT_ID = p_product_id;

    INSERT INTO ORDERS
    (
        ORDER_ID,
        PRODUCT_ID,
        USER_ID,
        QUANTITY,
        PRICE,
        STATUS,
        CREATED_AT
    )
    VALUES
    (
        ORDERS_SEQ.NEXTVAL,
        p_product_id,
        p_user_id,
        p_quantity,
        v_price,
        'PLACED',
        SYSTIMESTAMP
    );

    SP_UPDATE_STOCK(
        p_product_id,
        p_quantity
    );

    COMMIT;
END;
/

SELECT VIEW_NAME
FROM USER_VIEWS
WHERE VIEW_NAME LIKE 'VW%';

SELECT OBJECT_NAME
FROM USER_OBJECTS
WHERE OBJECT_TYPE='PROCEDURE'
AND OBJECT_NAME LIKE 'SP%';

BEGIN
FOR i IN 1..15 LOOP

INSERT INTO PRODUCTS
(
PRODUCT_ID,
PRODUCT_NAME,
PRICE,
DESCRIPTION,
CATEGORY,
BRAND,
STOCK,
IMAGE_URL,
RATING
)
VALUES
(
PRODUCT_SEQ.NEXTVAL,
'Men Shirt ' || i,
1500 + i*100,
'Premium Men Casual Shirt',
'Men',
'Urban Threads',
50,
'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab',
4.5
);

END LOOP;
COMMIT;
END;
/


BEGIN
FOR i IN 1..15 LOOP

INSERT INTO PRODUCTS
VALUES
(
PRODUCT_SEQ.NEXTVAL,
'Women Dress ' || i,
2500 + i*100,
'Premium Women Fashion Dress',
'Women',
'Elle & Co',
50,
'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f',
4.6
);

END LOOP;
COMMIT;
END;
/



BEGIN
FOR i IN 1..10 LOOP

INSERT INTO PRODUCTS
VALUES
(
PRODUCT_SEQ.NEXTVAL,
'Kids Wear ' || i,
1200,
'Kids Collection',
'Kids',
'Junior Style',
40,
'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea',
4.4
);

END LOOP;
COMMIT;
END;
/



BEGIN
FOR i IN 1..10 LOOP

INSERT INTO PRODUCTS
VALUES
(
PRODUCT_SEQ.NEXTVAL,
'Shoes ' || i,
3999,
'Running Shoes',
'Footwear',
'Stride',
30,
'https://images.unsplash.com/photo-1542291026-7eec264c27ff',
4.7
);

END LOOP;
COMMIT;
END;
/



BEGIN
FOR i IN 1..10 LOOP

INSERT INTO PRODUCTS
VALUES
(
PRODUCT_SEQ.NEXTVAL,
'Watch ' || i,
5999,
'Premium Watch',
'Accessories',
'Timepiece',
20,
'https://images.unsplash.com/photo-1523170335258-f5ed11844a49',
4.8
);

END LOOP;
COMMIT;
END;
/




BEGIN
FOR i IN 1..10 LOOP

INSERT INTO PRODUCTS
VALUES
(
PRODUCT_SEQ.NEXTVAL,
'Beauty Product ' || i,
1299,
'Skin Care Product',
'Beauty',
'Glow Beauty',
25,
'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9',
4.4
);

END LOOP;
COMMIT;
END;
/


SELECT CATEGORY, COUNT(*)
FROM PRODUCTS
GROUP BY CATEGORY;

ALTER TABLE PRODUCTS
MODIFY IMAGE_URL CLOB;

